### ISSUE TITLE
Add to manual/site.yml  the editurl line  and then edit the manual

### ISSUE THREAD

**Issue by rgleason** [LennartG-Sve/GPS-Odometer#12]
Add a site.yml similar to this one for Logbook  with and edit url!

```
site:
  title: Logbook
  url:  https://nowhere.net
  start_page: logbook:ROOT:index.adoc

content:
  sources:
    - url: ..
      start_path: manual
      branches: HEAD
      edit_url: https://github.com/opencpn-manuals/LogbookKonni_pi/edit/master/{path}      <--HERE

ui:   
  bundle:
    url: https://gitlab.com/leamas/antora-ui-default/-/raw/master/latest/ui-bundle.zip
    snapshot: true

output:
  dir: ./docs
  clean: true              


```

Push the change and then use the "Edit this page" in the upper right to add this.

> The Odometer has a filtering that dashboard does not use, e.g. it requires a certain number of satellites (4) and a HDOP level of 4 (not required by dashboard). These settings can be changed in the OpenCPN configuration file, e.g. increase HDOP to 6.
